# Generated by Django 5.1.7 on 2026-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0012_remove_classroom_teacher_join_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='messaging_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
